CREATE OR REPLACE TASK MTG_COST.PUBLIC.DAILY_MTG_PRICES_LOAD
WAREHOUSE = 'COMPUTE_WH'
SCHEDULE = 'USING CRON 30 4 * * * America/Los_Angeles' -- 4:30 AM PST daily
AS 
CALL MTG_COST.PUBLIC.LOAD_MTG_PRICES();

-- ALTER TASK MTG_COST.PUBLIC.DAILY_MTG_PRICES_LOAD RESUME;

-- SHOW TASKS IN SCHEMA MTG_COST.PUBLIC;