CREATE OR REPLACE PIPE MTG_COST.PUBLIC.mtg_prices_auto_ingest
AUTO_INGEST = TRUE
AS
COPY INTO MTG_COST.PUBLIC.MTG_PRICES 
FROM @s3_mtg_prices_stage 
FILE_FORMAT = (TYPE = 'PARQUET') 
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE 
ON_ERROR = 'CONTINUE';

-- SHOW PIPES IN SCHEMA MTG_COST.PUBLIC;