SELECT * FROM INFORMATION_SCHEMA.LOAD_HISTORY;

SELECT *
FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'MTG_PRICES',
    START_TIME => DATEADD(days, -7, CURRENT_TIMESTAMP())
))
ORDER BY file_name DESC;

SELECT *
FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'MTG_STATIC',
    START_TIME => DATEADD(days, -7, CURRENT_TIMESTAMP())
))
ORDER BY file_name DESC;