CREATE VIEW rolling_compute_costs AS

SELECT
  CASE 
    WHEN TO_CHAR(TO_DATE(START_TIME), 'YYYY-MM-DD') IS NULL THEN 'All'
    ELSE TO_CHAR(TO_DATE(START_TIME), 'YYYY-MM-DD')
  END AS day,
  ROUND(SUM(CREDITS_USED)*2,2) AS daily_usd,
  SUM(CREDITS_USED) AS daily_credits
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD(DAY, -30, CURRENT_DATE())
GROUP BY ROLLUP(TO_DATE(START_TIME))
ORDER BY day DESC;