CREATE OR REPLACE TABLE MTG_COST.PUBLIC.MTG_STATIC (
	,ID VARCHAR(36)
	,ORACLE_ID VARCHAR(36)
	,MTGO_ID NUMBER(10,0)
	,MTGO_FOIL_ID NUMBER(10,0)
	,TCGPLAYER_ID NUMBER(10,0)
	,CARDMARKET_ID NUMBER(10,0)
	,NAME VARCHAR(200)
	,LANG VARCHAR(5)
	,RELEASED_AT DATE
	,SET_NAME VARCHAR(100)
	,SET_ABBR VARCHAR(10)
	,SET_TYPE VARCHAR(50)
	,RARITY VARCHAR(20)
	,PULL_DATE DATE
	);